language: node_js
node_js:
  - 8
  - 10

jobs:
  include:
    - stage: test
      after_success: npm run coverage:ci
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
